"use client"
/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import useSWR, { SWRConfiguration, SWRResponse } from "swr"
import useSWRImmutable from "swr/immutable"
import useSWRMutation, { SWRMutationConfiguration, SWRMutationResponse } from "swr/mutation"
import * as runtime from "../runtime"

import { ChangePasswordRequest, UpdateUserRequest, UserDTO } from "../models"

/**
 * Change password of currently authenticated user (requires old password)
 * Change password
 */
export const useChangePassword = (() => {
  const fn = (
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Change password of currently authenticated user (requires old password)
 * Change password
 */
export const useChangePasswordImmutable = (() => {
  const fn = (
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Change password of currently authenticated user (requires old password)
 * Change password
 */
export const useChangePasswordMutation = (() => {
  const fn = (
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: (changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get profile of currently authenticated user
 * Get current user profile
 */
export const useGetCurrentUser = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,

    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get profile of currently authenticated user
 * Get current user profile
 */
export const useGetCurrentUserImmutable = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,

    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get profile of currently authenticated user
 * Get current user profile
 */
export const useGetCurrentUserMutation = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,

    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions of currently authenticated user
 * Get user permissions
 */
export const useGetCurrentUserPermissions = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions of currently authenticated user
 * Get user permissions
 */
export const useGetCurrentUserPermissionsImmutable = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions of currently authenticated user
 * Get user permissions
 */
export const useGetCurrentUserPermissionsMutation = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,

    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update profile of currently authenticated user (partial update)
 * Update current user profile
 */
export const useUpdateCurrentUser = (() => {
  const fn = (
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    updateUserRequest: UpdateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update profile of currently authenticated user (partial update)
 * Update current user profile
 */
export const useUpdateCurrentUserImmutable = (() => {
  const fn = (
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    updateUserRequest: UpdateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update profile of currently authenticated user (partial update)
 * Update current user profile
 */
export const useUpdateCurrentUserMutation = (() => {
  const fn = (
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    updateUserRequest: UpdateUserRequest,
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()
