/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SWRConfiguration } from "swr"
import { SWRMutationConfiguration } from "swr/mutation"
import * as runtime from "../runtime"

import * as swrs from "./AccountApiSwr"

import {
  ChangePasswordRequest,
  ChangePasswordRequestToJSON,
  UpdateUserRequest,
  UpdateUserRequestToJSON,
  UserDTO,
  UserDTOFromJSON,
} from "../models"

export interface ChangePasswordOperationRequest {
  changePasswordRequest: ChangePasswordRequest
}

export interface UpdateCurrentUserRequest {
  updateUserRequest: UpdateUserRequest
}

/**
 *
 */
export class AccountApi extends runtime.BaseAPI {
  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  protected changePasswordRequestOpts = (requestParameters: ChangePasswordOperationRequest): runtime.RequestOpts => {
    if (requestParameters.changePasswordRequest === null || requestParameters.changePasswordRequest === undefined) {
      throw new runtime.RequiredError(
        "changePasswordRequest",
        "Required parameter requestParameters.changePasswordRequest was null or undefined when calling changePassword.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    return {
      path: `/api/account/change-password`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ChangePasswordRequestToJSON(requestParameters.changePasswordRequest),
    }
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  protected changePasswordFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  protected changePasswordRaw = async (
    requestParameters: ChangePasswordOperationRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const context = this.changePasswordRequestOpts(requestParameters)
    return this.changePasswordFetch(context, initOverrides)
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  changePassword = async (changePasswordRequest: ChangePasswordRequest, initOverrides?: RequestInit): Promise<void> => {
    await this.changePasswordRaw({ changePasswordRequest: changePasswordRequest }, initOverrides)
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  useChangePassword = (changePasswordRequest: ChangePasswordRequest, config?: SWRConfiguration<void>) => {
    return swrs.useChangePassword(
      (changePasswordRequest: ChangePasswordRequest) =>
        this.changePasswordRequestOpts({ changePasswordRequest: changePasswordRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.changePasswordFetch(context)),
      changePasswordRequest,
      config,
    )
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  useChangePasswordImmutable = (changePasswordRequest: ChangePasswordRequest, config?: SWRConfiguration<void>) => {
    return swrs.useChangePasswordImmutable(
      (changePasswordRequest: ChangePasswordRequest) =>
        this.changePasswordRequestOpts({ changePasswordRequest: changePasswordRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.changePasswordFetch(context)),
      changePasswordRequest,
      config,
    )
  }

  /**
   * Change password of currently authenticated user (requires old password)
   * Change password
   */
  useChangePasswordMutation = (
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ) => {
    return swrs.useChangePasswordMutation(
      (changePasswordRequest: ChangePasswordRequest) =>
        this.changePasswordRequestOpts({ changePasswordRequest: changePasswordRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.changePasswordFetch(context)),
      changePasswordRequest,
      config,
    )
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  protected getCurrentUserRequestOpts = (): runtime.RequestOpts => {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    return {
      path: `/api/account`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  protected getCurrentUserFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<UserDTO>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue))
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  protected getCurrentUserRaw = async (initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserDTO>> => {
    const context = this.getCurrentUserRequestOpts()
    return this.getCurrentUserFetch(context, initOverrides)
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  getCurrentUser = async (initOverrides?: RequestInit): Promise<UserDTO> => {
    const response = await this.getCurrentUserRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  useGetCurrentUser = (config?: SWRConfiguration<UserDTO>) => {
    return swrs.useGetCurrentUser(
      () => this.getCurrentUserRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserFetch(context)),

      config,
    )
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  useGetCurrentUserImmutable = (config?: SWRConfiguration<UserDTO>) => {
    return swrs.useGetCurrentUserImmutable(
      () => this.getCurrentUserRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserFetch(context)),

      config,
    )
  }

  /**
   * Get profile of currently authenticated user
   * Get current user profile
   */
  useGetCurrentUserMutation = (config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>) => {
    return swrs.useGetCurrentUserMutation(
      () => this.getCurrentUserRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserFetch(context)),

      config,
    )
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  protected getCurrentUserPermissionsRequestOpts = (): runtime.RequestOpts => {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    return {
      path: `/api/account/permissions`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  protected getCurrentUserPermissionsFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  protected getCurrentUserPermissionsRaw = async (initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> => {
    const context = this.getCurrentUserPermissionsRequestOpts()
    return this.getCurrentUserPermissionsFetch(context, initOverrides)
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  getCurrentUserPermissions = async (initOverrides?: RequestInit): Promise<void> => {
    await this.getCurrentUserPermissionsRaw(initOverrides)
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  useGetCurrentUserPermissions = (config?: SWRConfiguration<void>) => {
    return swrs.useGetCurrentUserPermissions(
      () => this.getCurrentUserPermissionsRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserPermissionsFetch(context)),

      config,
    )
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  useGetCurrentUserPermissionsImmutable = (config?: SWRConfiguration<void>) => {
    return swrs.useGetCurrentUserPermissionsImmutable(
      () => this.getCurrentUserPermissionsRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserPermissionsFetch(context)),

      config,
    )
  }

  /**
   * Get final computed permissions of currently authenticated user
   * Get user permissions
   */
  useGetCurrentUserPermissionsMutation = (config?: SWRMutationConfiguration<void, any, string, never, void>) => {
    return swrs.useGetCurrentUserPermissionsMutation(
      () => this.getCurrentUserPermissionsRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.getCurrentUserPermissionsFetch(context)),

      config,
    )
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  protected updateCurrentUserRequestOpts = (requestParameters: UpdateCurrentUserRequest): runtime.RequestOpts => {
    if (requestParameters.updateUserRequest === null || requestParameters.updateUserRequest === undefined) {
      throw new runtime.RequiredError(
        "updateUserRequest",
        "Required parameter requestParameters.updateUserRequest was null or undefined when calling updateCurrentUser.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    return {
      path: `/api/account`,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateUserRequestToJSON(requestParameters.updateUserRequest),
    }
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  protected updateCurrentUserFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<UserDTO>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue))
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  protected updateCurrentUserRaw = async (
    requestParameters: UpdateCurrentUserRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<UserDTO>> => {
    const context = this.updateCurrentUserRequestOpts(requestParameters)
    return this.updateCurrentUserFetch(context, initOverrides)
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  updateCurrentUser = async (updateUserRequest: UpdateUserRequest, initOverrides?: RequestInit): Promise<UserDTO> => {
    const response = await this.updateCurrentUserRaw({ updateUserRequest: updateUserRequest }, initOverrides)
    return await response.value()
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  useUpdateCurrentUser = (updateUserRequest: UpdateUserRequest, config?: SWRConfiguration<UserDTO>) => {
    return swrs.useUpdateCurrentUser(
      (updateUserRequest: UpdateUserRequest) =>
        this.updateCurrentUserRequestOpts({ updateUserRequest: updateUserRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.updateCurrentUserFetch(context)),
      updateUserRequest,
      config,
    )
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  useUpdateCurrentUserImmutable = (updateUserRequest: UpdateUserRequest, config?: SWRConfiguration<UserDTO>) => {
    return swrs.useUpdateCurrentUserImmutable(
      (updateUserRequest: UpdateUserRequest) =>
        this.updateCurrentUserRequestOpts({ updateUserRequest: updateUserRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.updateCurrentUserFetch(context)),
      updateUserRequest,
      config,
    )
  }

  /**
   * Update profile of currently authenticated user (partial update)
   * Update current user profile
   */
  useUpdateCurrentUserMutation = (
    updateUserRequest: UpdateUserRequest,
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ) => {
    return swrs.useUpdateCurrentUserMutation(
      (updateUserRequest: UpdateUserRequest) =>
        this.updateCurrentUserRequestOpts({ updateUserRequest: updateUserRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.updateCurrentUserFetch(context)),
      updateUserRequest,
      config,
    )
  }
}
