"use client"
/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import useSWR, { SWRConfiguration, SWRResponse } from "swr"
import useSWRImmutable from "swr/immutable"
import useSWRMutation, { SWRMutationConfiguration, SWRMutationResponse } from "swr/mutation"
import * as runtime from "../runtime"

import {
  ChangePasswordRequest,
  CreateUserRequest,
  Page,
  Pageable,
  RoleDTO,
  UpdateUserRequest,
  UserDTO,
} from "../models"

/**
 * Change user password without requiring old password (admin mode)
 * Change user password (admin)
 */
export const useChangeUserPassword = (() => {
  const fn = (
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(id, changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Change user password without requiring old password (admin mode)
 * Change user password (admin)
 */
export const useChangeUserPasswordImmutable = (() => {
  const fn = (
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(id, changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Change user password without requiring old password (admin mode)
 * Change user password (admin)
 */
export const useChangeUserPasswordMutation = (() => {
  const fn = (
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,
    id: string,
    changePasswordRequest: ChangePasswordRequest,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: (id: string, changePasswordRequest: ChangePasswordRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(id, changePasswordRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Create new user with roles
 * Create user
 */
export const useCreateUser = (() => {
  const fn = (
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    createUserRequest: CreateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(createUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Create new user with roles
 * Create user
 */
export const useCreateUserImmutable = (() => {
  const fn = (
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    createUserRequest: CreateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(createUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Create new user with roles
 * Create user
 */
export const useCreateUserMutation = (() => {
  const fn = (
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    createUserRequest: CreateUserRequest,
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (createUserRequest: CreateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(createUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Delete user by ID (physical deletion)
 * Delete user
 */
export const useDeleteUser = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Delete user by ID (physical deletion)
 * Delete user
 */
export const useDeleteUserImmutable = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Delete user by ID (physical deletion)
 * Delete user
 */
export const useDeleteUserMutation = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,
    id: string,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all permissions (sorted by module, code)
 * Get all permissions
 */
export const useGetAllPermissions = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all permissions (sorted by module, code)
 * Get all permissions
 */
export const useGetAllPermissionsImmutable = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all permissions (sorted by module, code)
 * Get all permissions
 */
export const useGetAllPermissionsMutation = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,

    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all roles with their permissions
 * Get all roles
 */
export const useGetAllRoles = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all roles with their permissions
 * Get all roles
 */
export const useGetAllRolesImmutable = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get list of all roles with their permissions
 * Get all roles
 */
export const useGetAllRolesMutation = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,

    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get paginated list of all users (without roles/permissions for performance)
 * Get all users
 */
export const useGetAllUsers = (() => {
  const fn = (
    key: (pageable: Pageable) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<Page>,
    pageable: Pageable,
    config?: SWRConfiguration<Page>,
  ): SWRResponse<Page> & {
    key: (pageable: Pageable) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<Page>(() => key(pageable), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get paginated list of all users (without roles/permissions for performance)
 * Get all users
 */
export const useGetAllUsersImmutable = (() => {
  const fn = (
    key: (pageable: Pageable) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<Page>,
    pageable: Pageable,
    config?: SWRConfiguration<Page>,
  ): SWRResponse<Page> & {
    key: (pageable: Pageable) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<Page>(() => key(pageable), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get paginated list of all users (without roles/permissions for performance)
 * Get all users
 */
export const useGetAllUsersMutation = (() => {
  const fn = (
    key: (pageable: Pageable) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<Page>,
    pageable: Pageable,
    config?: SWRMutationConfiguration<Page, any, string, never, Page>,
  ): SWRMutationResponse<Page> & {
    key: (pageable: Pageable) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<Page>(() => key(pageable), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get role details by ID (with permissions)
 * Get role by ID
 */
export const useGetRoleById = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<RoleDTO>,
    id: string,
    config?: SWRConfiguration<RoleDTO>,
  ): SWRResponse<RoleDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<RoleDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get role details by ID (with permissions)
 * Get role by ID
 */
export const useGetRoleByIdImmutable = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<RoleDTO>,
    id: string,
    config?: SWRConfiguration<RoleDTO>,
  ): SWRResponse<RoleDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<RoleDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get role details by ID (with permissions)
 * Get role by ID
 */
export const useGetRoleByIdMutation = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<RoleDTO>,
    id: string,
    config?: SWRMutationConfiguration<RoleDTO, any, string, never, RoleDTO>,
  ): SWRMutationResponse<RoleDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<RoleDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get user details by ID (with roles)
 * Get user by ID
 */
export const useGetUserById = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get user details by ID (with roles)
 * Get user by ID
 */
export const useGetUserByIdImmutable = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get user details by ID (with roles)
 * Get user by ID
 */
export const useGetUserByIdMutation = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    id: string,
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions for specific user
 * Get user permissions
 */
export const useGetUserPermissions = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions for specific user
 * Get user permissions
 */
export const useGetUserPermissionsImmutable = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    id: string,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Get final computed permissions for specific user
 * Get user permissions
 */
export const useGetUserPermissionsMutation = (() => {
  const fn = (
    key: (id: string) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,
    id: string,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: (id: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(id), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Search users by username, email, firstName or lastName (case-insensitive)
 * Search users
 */
export const useSearchUsers = (() => {
  const fn = (
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<Page>,
    pageable: Pageable,
    q?: string,
    config?: SWRConfiguration<Page>,
  ): SWRResponse<Page> & {
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<Page>(() => key(pageable, q), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Search users by username, email, firstName or lastName (case-insensitive)
 * Search users
 */
export const useSearchUsersImmutable = (() => {
  const fn = (
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<Page>,
    pageable: Pageable,
    q?: string,
    config?: SWRConfiguration<Page>,
  ): SWRResponse<Page> & {
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<Page>(() => key(pageable, q), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Search users by username, email, firstName or lastName (case-insensitive)
 * Search users
 */
export const useSearchUsersMutation = (() => {
  const fn = (
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<Page>,
    pageable: Pageable,
    q?: string,
    config?: SWRMutationConfiguration<Page, any, string, never, Page>,
  ): SWRMutationResponse<Page> & {
    key: (pageable: Pageable, q?: string) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<Page>(() => key(pageable, q), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Lock or unlock user account
 * Toggle user lock
 */
export const useToggleUserLock = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Lock or unlock user account
 * Toggle user lock
 */
export const useToggleUserLockImmutable = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Lock or unlock user account
 * Toggle user lock
 */
export const useToggleUserLockMutation = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Enable or disable user account
 * Toggle user status
 */
export const useToggleUserStatus = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Enable or disable user account
 * Toggle user status
 */
export const useToggleUserStatusImmutable = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Enable or disable user account
 * Toggle user status
 */
export const useToggleUserStatusMutation = (() => {
  const fn = (
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    id: string,
    requestBody: { [key: string]: boolean },
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (id: string, requestBody: { [key: string]: boolean }) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(id, requestBody), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update existing user (partial update)
 * Update user
 */
export const useUpdateUser = (() => {
  const fn = (
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    updateUserRequest: UpdateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<UserDTO>(() => key(id, updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update existing user (partial update)
 * Update user
 */
export const useUpdateUserImmutable = (() => {
  const fn = (
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<UserDTO>,
    id: string,
    updateUserRequest: UpdateUserRequest,
    config?: SWRConfiguration<UserDTO>,
  ): SWRResponse<UserDTO> & {
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<UserDTO>(() => key(id, updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Update existing user (partial update)
 * Update user
 */
export const useUpdateUserMutation = (() => {
  const fn = (
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<UserDTO>,
    id: string,
    updateUserRequest: UpdateUserRequest,
    config?: SWRMutationConfiguration<UserDTO, any, string, never, UserDTO>,
  ): SWRMutationResponse<UserDTO> & {
    key: (id: string, updateUserRequest: UpdateUserRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<UserDTO>(() => key(id, updateUserRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()
