/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SWRConfiguration } from "swr"
import { SWRMutationConfiguration } from "swr/mutation"
import * as runtime from "../runtime"

import * as swrs from "./AuthenticationApiSwr"

import {
  LoginRequest,
  LoginRequestToJSON,
  RefreshTokenRequest,
  RefreshTokenRequestToJSON,
  TokenResponse,
  TokenResponseFromJSON,
} from "../models"

export interface LoginOperationRequest {
  loginRequest: LoginRequest
}

export interface LogoutRequest {
  refreshTokenRequest: RefreshTokenRequest
}

export interface RefreshRequest {
  refreshTokenRequest: RefreshTokenRequest
}

/**
 *
 */
export class AuthenticationApi extends runtime.BaseAPI {
  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  protected authenticateRequestOpts = (): runtime.RequestOpts => {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    return {
      path: `/api/auth/authenticate`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  protected authenticateFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  protected authenticateRaw = async (initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> => {
    const context = this.authenticateRequestOpts()
    return this.authenticateFetch(context, initOverrides)
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  authenticate = async (initOverrides?: RequestInit): Promise<void> => {
    await this.authenticateRaw(initOverrides)
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  useAuthenticate = (config?: SWRConfiguration<void>) => {
    return swrs.useAuthenticate(
      () => this.authenticateRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.authenticateFetch(context)),

      config,
    )
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  useAuthenticateImmutable = (config?: SWRConfiguration<void>) => {
    return swrs.useAuthenticateImmutable(
      () => this.authenticateRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.authenticateFetch(context)),

      config,
    )
  }

  /**
   * Check if user is authenticated (requires valid JWT token)
   * Check authentication
   */
  useAuthenticateMutation = (config?: SWRMutationConfiguration<void, any, string, never, void>) => {
    return swrs.useAuthenticateMutation(
      () => this.authenticateRequestOpts(),
      (context: runtime.RequestOpts) => this.swrFetch(this.authenticateFetch(context)),

      config,
    )
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  protected loginRequestOpts = (requestParameters: LoginOperationRequest): runtime.RequestOpts => {
    if (requestParameters.loginRequest === null || requestParameters.loginRequest === undefined) {
      throw new runtime.RequiredError(
        "loginRequest",
        "Required parameter requestParameters.loginRequest was null or undefined when calling login.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    return {
      path: `/api/auth/login`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters.loginRequest),
    }
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  protected loginFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<TokenResponse>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue))
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  protected loginRaw = async (
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<TokenResponse>> => {
    const context = this.loginRequestOpts(requestParameters)
    return this.loginFetch(context, initOverrides)
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  login = async (loginRequest: LoginRequest, initOverrides?: RequestInit): Promise<TokenResponse> => {
    const response = await this.loginRaw({ loginRequest: loginRequest }, initOverrides)
    return await response.value()
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  useLogin = (loginRequest: LoginRequest, config?: SWRConfiguration<TokenResponse>) => {
    return swrs.useLogin(
      (loginRequest: LoginRequest) => this.loginRequestOpts({ loginRequest: loginRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.loginFetch(context)),
      loginRequest,
      config,
    )
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  useLoginImmutable = (loginRequest: LoginRequest, config?: SWRConfiguration<TokenResponse>) => {
    return swrs.useLoginImmutable(
      (loginRequest: LoginRequest) => this.loginRequestOpts({ loginRequest: loginRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.loginFetch(context)),
      loginRequest,
      config,
    )
  }

  /**
   * Authenticate user with username and password, returns JWT tokens
   * Login
   */
  useLoginMutation = (
    loginRequest: LoginRequest,
    config?: SWRMutationConfiguration<TokenResponse, any, string, never, TokenResponse>,
  ) => {
    return swrs.useLoginMutation(
      (loginRequest: LoginRequest) => this.loginRequestOpts({ loginRequest: loginRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.loginFetch(context)),
      loginRequest,
      config,
    )
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  protected logoutRequestOpts = (requestParameters: LogoutRequest): runtime.RequestOpts => {
    if (requestParameters.refreshTokenRequest === null || requestParameters.refreshTokenRequest === undefined) {
      throw new runtime.RequiredError(
        "refreshTokenRequest",
        "Required parameter requestParameters.refreshTokenRequest was null or undefined when calling logout.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    return {
      path: `/api/auth/logout`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: RefreshTokenRequestToJSON(requestParameters.refreshTokenRequest),
    }
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  protected logoutFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  protected logoutRaw = async (
    requestParameters: LogoutRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> => {
    const context = this.logoutRequestOpts(requestParameters)
    return this.logoutFetch(context, initOverrides)
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  logout = async (refreshTokenRequest: RefreshTokenRequest, initOverrides?: RequestInit): Promise<void> => {
    await this.logoutRaw({ refreshTokenRequest: refreshTokenRequest }, initOverrides)
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  useLogout = (refreshTokenRequest: RefreshTokenRequest, config?: SWRConfiguration<void>) => {
    return swrs.useLogout(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.logoutRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.logoutFetch(context)),
      refreshTokenRequest,
      config,
    )
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  useLogoutImmutable = (refreshTokenRequest: RefreshTokenRequest, config?: SWRConfiguration<void>) => {
    return swrs.useLogoutImmutable(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.logoutRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.logoutFetch(context)),
      refreshTokenRequest,
      config,
    )
  }

  /**
   * Invalidate refresh token (access token remains valid until expiration)
   * Logout
   */
  useLogoutMutation = (
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ) => {
    return swrs.useLogoutMutation(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.logoutRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.logoutFetch(context)),
      refreshTokenRequest,
      config,
    )
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  protected refreshRequestOpts = (requestParameters: RefreshRequest): runtime.RequestOpts => {
    if (requestParameters.refreshTokenRequest === null || requestParameters.refreshTokenRequest === undefined) {
      throw new runtime.RequiredError(
        "refreshTokenRequest",
        "Required parameter requestParameters.refreshTokenRequest was null or undefined when calling refresh.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    return {
      path: `/api/auth/refresh`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: RefreshTokenRequestToJSON(requestParameters.refreshTokenRequest),
    }
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  protected refreshFetch = async (
    context: runtime.RequestOpts,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<TokenResponse>> => {
    const response = await this.request(context, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue))
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  protected refreshRaw = async (
    requestParameters: RefreshRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<TokenResponse>> => {
    const context = this.refreshRequestOpts(requestParameters)
    return this.refreshFetch(context, initOverrides)
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  refresh = async (refreshTokenRequest: RefreshTokenRequest, initOverrides?: RequestInit): Promise<TokenResponse> => {
    const response = await this.refreshRaw({ refreshTokenRequest: refreshTokenRequest }, initOverrides)
    return await response.value()
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  useRefresh = (refreshTokenRequest: RefreshTokenRequest, config?: SWRConfiguration<TokenResponse>) => {
    return swrs.useRefresh(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.refreshRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.refreshFetch(context)),
      refreshTokenRequest,
      config,
    )
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  useRefreshImmutable = (refreshTokenRequest: RefreshTokenRequest, config?: SWRConfiguration<TokenResponse>) => {
    return swrs.useRefreshImmutable(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.refreshRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.refreshFetch(context)),
      refreshTokenRequest,
      config,
    )
  }

  /**
   * Exchange refresh token for new access token
   * Refresh token
   */
  useRefreshMutation = (
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRMutationConfiguration<TokenResponse, any, string, never, TokenResponse>,
  ) => {
    return swrs.useRefreshMutation(
      (refreshTokenRequest: RefreshTokenRequest) =>
        this.refreshRequestOpts({ refreshTokenRequest: refreshTokenRequest }),
      (context: runtime.RequestOpts) => this.swrFetch(this.refreshFetch(context)),
      refreshTokenRequest,
      config,
    )
  }
}
