"use client"
/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import useSWR, { SWRConfiguration, SWRResponse } from "swr"
import useSWRImmutable from "swr/immutable"
import useSWRMutation, { SWRMutationConfiguration, SWRMutationResponse } from "swr/mutation"
import * as runtime from "../runtime"

import { LoginRequest, RefreshTokenRequest, TokenResponse } from "../models"

/**
 * Check if user is authenticated (requires valid JWT token)
 * Check authentication
 */
export const useAuthenticate = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Check if user is authenticated (requires valid JWT token)
 * Check authentication
 */
export const useAuthenticateImmutable = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,

    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Check if user is authenticated (requires valid JWT token)
 * Check authentication
 */
export const useAuthenticateMutation = (() => {
  const fn = (
    key: () => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,

    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: () => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Authenticate user with username and password, returns JWT tokens
 * Login
 */
export const useLogin = (() => {
  const fn = (
    key: (loginRequest: LoginRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<TokenResponse>,
    loginRequest: LoginRequest,
    config?: SWRConfiguration<TokenResponse>,
  ): SWRResponse<TokenResponse> & {
    key: (loginRequest: LoginRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<TokenResponse>(() => key(loginRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Authenticate user with username and password, returns JWT tokens
 * Login
 */
export const useLoginImmutable = (() => {
  const fn = (
    key: (loginRequest: LoginRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<TokenResponse>,
    loginRequest: LoginRequest,
    config?: SWRConfiguration<TokenResponse>,
  ): SWRResponse<TokenResponse> & {
    key: (loginRequest: LoginRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<TokenResponse>(() => key(loginRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Authenticate user with username and password, returns JWT tokens
 * Login
 */
export const useLoginMutation = (() => {
  const fn = (
    key: (loginRequest: LoginRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<TokenResponse>,
    loginRequest: LoginRequest,
    config?: SWRMutationConfiguration<TokenResponse, any, string, never, TokenResponse>,
  ): SWRMutationResponse<TokenResponse> & {
    key: (loginRequest: LoginRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<TokenResponse>(() => key(loginRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Invalidate refresh token (access token remains valid until expiration)
 * Logout
 */
export const useLogout = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<void>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Invalidate refresh token (access token remains valid until expiration)
 * Logout
 */
export const useLogoutImmutable = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<void>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRConfiguration<void>,
  ): SWRResponse<void> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<void>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Invalidate refresh token (access token remains valid until expiration)
 * Logout
 */
export const useLogoutMutation = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<void>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRMutationConfiguration<void, any, string, never, void>,
  ): SWRMutationResponse<void> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<void>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Exchange refresh token for new access token
 * Refresh token
 */
export const useRefresh = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<TokenResponse>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRConfiguration<TokenResponse>,
  ): SWRResponse<TokenResponse> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWR<TokenResponse>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Exchange refresh token for new access token
 * Refresh token
 */
export const useRefreshImmutable = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (context: runtime.RequestOpts) => Promise<TokenResponse>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRConfiguration<TokenResponse>,
  ): SWRResponse<TokenResponse> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRImmutable<TokenResponse>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()

/**
 * Exchange refresh token for new access token
 * Refresh token
 */
export const useRefreshMutation = (() => {
  const fn = (
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts,
    fetcher: (args: any) => Promise<TokenResponse>,
    refreshTokenRequest: RefreshTokenRequest,
    config?: SWRMutationConfiguration<TokenResponse, any, string, never, TokenResponse>,
  ): SWRMutationResponse<TokenResponse> & {
    key: (refreshTokenRequest: RefreshTokenRequest) => runtime.RequestOpts
  } => {
    return {
      ...useSWRMutation<TokenResponse>(() => key(refreshTokenRequest), fetcher, config),
      key: key,
    }
  }
  return fn
})()
