/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime"
/**
 *
 * @export
 * @interface Language
 */
export interface Language {
  /**
   *
   * @type {number}
   * @memberof Language
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof Language
   */
  langCode?: string
  /**
   *
   * @type {string}
   * @memberof Language
   */
  countryCode?: string
  /**
   *
   * @type {string}
   * @memberof Language
   */
  name?: string
  /**
   *
   * @type {boolean}
   * @memberof Language
   */
  isActive?: boolean
  /**
   *
   * @type {number}
   * @memberof Language
   */
  displayOrder?: number
  /**
   *
   * @type {Date}
   * @memberof Language
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof Language
   */
  updatedAt?: Date
}

export function LanguageFromJSON(json: any): Language {
  return LanguageFromJSONTyped(json, false)
}

export function LanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Language {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    langCode: !exists(json, "langCode") ? undefined : json["langCode"],
    countryCode: !exists(json, "countryCode") ? undefined : json["countryCode"],
    name: !exists(json, "name") ? undefined : json["name"],
    isActive: !exists(json, "isActive") ? undefined : json["isActive"],
    displayOrder: !exists(json, "displayOrder") ? undefined : json["displayOrder"],
    createdAt: !exists(json, "createdAt") ? undefined : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt") ? undefined : new Date(json["updatedAt"]),
  }
}

export function LanguageToJSON(value?: Language | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    langCode: value.langCode,
    countryCode: value.countryCode,
    name: value.name,
    isActive: value.isActive,
    displayOrder: value.displayOrder,
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
  }
}
