/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime"
import { SortObject, SortObjectFromJSON, SortObjectToJSON } from "./SortObject"

/**
 *
 * @export
 * @interface PageableObject
 */
export interface PageableObject {
  /**
   *
   * @type {boolean}
   * @memberof PageableObject
   */
  paged?: boolean
  /**
   *
   * @type {number}
   * @memberof PageableObject
   */
  pageNumber?: number
  /**
   *
   * @type {number}
   * @memberof PageableObject
   */
  pageSize?: number
  /**
   *
   * @type {number}
   * @memberof PageableObject
   */
  offset?: number
  /**
   *
   * @type {SortObject}
   * @memberof PageableObject
   */
  sort?: SortObject
  /**
   *
   * @type {boolean}
   * @memberof PageableObject
   */
  unpaged?: boolean
}

export function PageableObjectFromJSON(json: any): PageableObject {
  return PageableObjectFromJSONTyped(json, false)
}

export function PageableObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableObject {
  if (json === undefined || json === null) {
    return json
  }
  return {
    paged: !exists(json, "paged") ? undefined : json["paged"],
    pageNumber: !exists(json, "pageNumber") ? undefined : json["pageNumber"],
    pageSize: !exists(json, "pageSize") ? undefined : json["pageSize"],
    offset: !exists(json, "offset") ? undefined : json["offset"],
    sort: !exists(json, "sort") ? undefined : SortObjectFromJSON(json["sort"]),
    unpaged: !exists(json, "unpaged") ? undefined : json["unpaged"],
  }
}

export function PageableObjectToJSON(value?: PageableObject | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    paged: value.paged,
    pageNumber: value.pageNumber,
    pageSize: value.pageSize,
    offset: value.offset,
    sort: SortObjectToJSON(value.sort),
    unpaged: value.unpaged,
  }
}
