/* tslint:disable */
/* eslint-disable */
/**
 * RAISER - Warehouse Management System API
 * REST API для системы складского учёта RAISER.  ## Аутентификация  API поддерживает два метода аутентификации:  ### 🔐 Метод 1: JWT Bearer Token (рекомендуется) 1. POST /api/auth/login - получить access token и refresh token 2. Используйте access token для всех защищённых endpoints 3. POST /api/auth/refresh - обновить access token (когда истечёт)  **Преимущества:** - ✅ Stateless (не нужна session на сервере) - ✅ Безопасно для production - ✅ Поддержка refresh tokens - ✅ Масштабируется горизонтально  ### 🔓 Метод 2: HTTP Basic Authentication (только dev/staging!) Отправляйте username и password в каждом request.  **Использовать только для:** - ✅ Быстрого тестирования в Swagger UI - ✅ Dev/Staging окружений - ❌ НЕ использовать в production без HTTPS!  ### Авторизация (Permission-based RBAC) Система использует права доступа (permissions): - Permissions (права): USER_VIEW, USER_CREATE, USER_EDIT, INVENTORY_WRITE, etc. - Roles (роли): ADMIN, WR_KEEPER, USER - User-level overrides: permissionsAdd, permissionsRemove - Финальные права: (role_permissions ∪ permissionsAdd) − permissionsRemove  ## Типичный workflow:  **С JWT:** 1. POST /api/auth/login → получить accessToken 2. Нажать \"Authorize\" → выбрать \"Bearer Authentication\" 3. Вставить токен → Authorize 4. Использовать API endpoints  **С Basic Auth (только dev/staging):** 1. Нажать \"Authorize\" → выбрать \"Basic Authentication\" 2. Ввести username и password → Authorize 3. Использовать API endpoints (credentials отправляются автоматически)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@raiser.uz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime"
/**
 *
 * @export
 * @interface SortObject
 */
export interface SortObject {
  /**
   *
   * @type {boolean}
   * @memberof SortObject
   */
  sorted?: boolean
  /**
   *
   * @type {boolean}
   * @memberof SortObject
   */
  empty?: boolean
  /**
   *
   * @type {boolean}
   * @memberof SortObject
   */
  unsorted?: boolean
}

export function SortObjectFromJSON(json: any): SortObject {
  return SortObjectFromJSONTyped(json, false)
}

export function SortObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortObject {
  if (json === undefined || json === null) {
    return json
  }
  return {
    sorted: !exists(json, "sorted") ? undefined : json["sorted"],
    empty: !exists(json, "empty") ? undefined : json["empty"],
    unsorted: !exists(json, "unsorted") ? undefined : json["unsorted"],
  }
}

export function SortObjectToJSON(value?: SortObject | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    sorted: value.sorted,
    empty: value.empty,
    unsorted: value.unsorted,
  }
}
